### ISSUE TITLE
License and collaboration

### ISSUE THREAD

**Issue by jdubuisson** [Dowdow/LeagueOfLegendsAPIBundle#4]
Hi @Dowdow ,

There are two contributors : you and myself. If you agree, can we license the bundle under the GPLv3 ? (There is no license for now)

I'll be using this bundle (as I have in the past) and I would like to help improve/update it. I have no issue with proposing pull requests, however it would be easier if you would agree to add me as a collaborator. This may be a bold request (I do not know GitHub's etiquette very well) but you stated that you're no longer working on the bundle. So I guess this is ok :sweat_smile: 

What do you think ?

**Comment by Dowdow** [comment]
Hi !

Thanks for asking ! Like I said in another post (I don't remember where ...), I no longer have the time to contribute to this project. But if you want to continue, I give you all the access !

If I remember, the worst part of this bundle is the Doctrine Entity because I tryied to keep the data structure form Riot API but I think it's a mistake. Furthermore the API have changed a little bit so some components shouldn't be up to date.

Good luck in your dev and if you want some informations I'm always available !
